---
sudo: false
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
language: ruby
branches:
  only:
    - master
matrix:
  fast_finish: true
  include:
  - rvm: 2.2.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.2.3
    env: PUPPET_GEM_VERSION="~> 3.7"
notifications:
  email: false
